---
name: Build English-Esperanto dictionary

on:
  push: 
    branches: [main]
  schedule:
    - cron: "0 0 * * SAT"

permissions:
  contents: write # This is required for actions/checkout

jobs:
  generate_dictionary:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch and convert English-Esperanto dictionary
        run: |
          sudo apt-get update && sudo apt-get install -y stardict-tools curl
          curl http://www.denisowski.org/Esperanto/ESPDIC/espdic.txt | sort -u -t: -k1,1 | sed "s/ : /\t/g" > /tmp/en-eo
          cd /tmp
          /usr/lib/stardict-tools/tabfile /tmp/en-eo
          tar -czvf /tmp/dictionary.tar.gz -C /tmp/en-eo*
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "en-eo stardict format dictionary"
          files: |
            /tmp/dictionary.tar.gz
